package com.amazon.ingestion.seeding;

import com.amazon.ingestion.schema.CorpusSchema;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates a durable, reusable PlateJS corpus file from the local prod export.
 *
 * <p>Input: {@code source_with_content.jsonl} - 56 real prod FAQ records whose body is
 * HTML-scraped <b>markdown</b> and whose scope fields are top-level comma-joined strings.
 *
 * <p>Output: a JSONL file where each line is a COREx-node-shaped record matching what the live
 * {@code getContentNodes} API returns - body lifted into the real {@code system_rte_v2}
 * <b>PlateJS</b> envelope, and scope packed into a {@code metadata} JSON string using the real
 * built-in keys ({@code system_job-level}, {@code system_employee-class}) plus a versioned
 * {@code content-type-16 = "Skywalker FAQ"}. This is the "what we would run through our own
 * system" artifact, saved for later reuse so it never has to be regenerated by hand.
 *
 * <p>Run as a plain main (see {@code README} / steering for the exact command). It performs no
 * network or AWS calls - pure local transform.
 */
public final class PlateJsCorpusGenerator {

    private static final ObjectMapper JSON = new ObjectMapper();

    private PlateJsCorpusGenerator() {
    }

    public static void main(String[] args) throws Exception {
        if (args.length < 2) {
            System.err.println("usage: PlateJsCorpusGenerator <input.jsonl> <output platejs.jsonl>");
            System.exit(2);
        }
        Path in = Path.of(args[0]);
        Path out = Path.of(args[1]);

        List<String> outLines = new ArrayList<>();
        int converted = 0;
        for (String line : Files.readAllLines(in, StandardCharsets.UTF_8)) {
            if (line.isBlank()) {
                continue;
            }
            JsonNode r = JSON.readTree(line);
            ObjectNode node = toCorexNode(r);
            outLines.add(JSON.writeValueAsString(node));
            converted++;
        }
        Files.write(out, outLines, StandardCharsets.UTF_8);
        System.out.println("Converted " + converted + " records to PlateJS corpus: " + out);
    }

    /**
     * Build one COREx-node-shaped record: PlateJS content envelope + reconstructed metadata.
     */
    private static ObjectNode toCorexNode(JsonNode r) {
        ObjectNode node = JSON.createObjectNode();
        node.put("nodeId", r.path("nodeId").asText());
        node.put("title", r.path("title").asText(""));
        node.put("version", r.path("version").asText("0.0.0"));
        node.put("status", r.path("status").asText("DRAFT"));
        node.put("language", r.path("language").asText("en"));
        if (r.has("lastModifiedDate")) {
            node.set("lastModifiedDate", r.get("lastModifiedDate"));
        }

        // geography: top-level array of real values (split the comma-joined export string).
        node.set("geography", toArray(CorpusSchema.splitScope(r.path("geography").asText(""))));

        // topics: drop the leading UUID the export sometimes prefixes; keep readable labels.
        ArrayNode topics = JSON.createArrayNode();
        for (String t : CorpusSchema.splitScope(r.path("topics").asText(""))) {
            if (!t.matches("[0-9a-fA-F-]{32,36}")) {
                topics.add(t);
            }
        }
        node.set("topics", topics);

        // lineOfBusiness: real top-level field (COREx comma-joined). Kept top-level so the
        // assembler preserves it in source_metadata. It is no longer promoted to a dedicated
        // indexed filter field (the T18 line_of_business promotion was removed); it lives only
        // inside the flat_object source_metadata blob.
        node.set("lineOfBusiness", toArray(CorpusSchema.splitScope(r.path("lineOfBusiness").asText(""))));

        // content: real PlateJS RTE_V2 envelope, lifted from the export's markdown.
        node.put("content", MarkdownToPlateJs.toContentEnvelope(r.path("markdown").asText("")));

        // metadata: reconstruct the real built-in scope keys + a versioned content-type, as a
        // JSON string (exactly how COREx returns the metadata field).
        ObjectNode metadata = JSON.createObjectNode();
        metadata.set(CorpusSchema.FIELD_JOB_LEVEL, toArray(CorpusSchema.splitScope(r.path("jobLevel").asText(""))));
        metadata.set(CorpusSchema.FIELD_EMPLOYEE_CLASS,
                toArray(CorpusSchema.splitScope(r.path("employeeClass").asText(""))));
        // Versioned custom content-type, value-resolved to "Skywalker FAQ" (the corpus marker).
        metadata.put("content-type-16", CorpusSchema.CONTENT_TYPE);
        node.put("metadata", metadata.toString());

        return node;
    }

    private static ArrayNode toArray(List<String> values) {
        ArrayNode a = JSON.createArrayNode();
        for (String v : values) {
            a.add(v);
        }
        return a;
    }
}
